#! python


def build(ctx):
    for model in 'baseline', 'endogenous_job_finding_duration':
        source = 'graph_equivalents'
        ctx(
            features='run_m_script',
            source='graph_equivalents.m',
            target=[ctx.path_to(ctx, 'OUT_FIGURES', 'cash_equivalent_ue_vs_e_{}.png'.format(model)),
                    ctx.path_to(ctx, 'OUT_FIGURES', 'cash_equivalent_total_{}.png'.format(model)),
                    ctx.path_to(ctx, 'OUT_FIGURES', 'consumption_equivalent_ue_vs_e_{}.png'.format(model)),
                    ctx.path_to(ctx, 'OUT_FIGURES', 'consumption_equivalent_total_{}.png').format(model),
                    ctx.path_to(ctx, 'OUT_FIGURES', 'consumption_vs_cash_equivalent_{}.png'.format(model)),
                    ctx.path_to(ctx, 'OUT_FIGURES', 'consumption_equivalent_vs_wealth_{}.png'.format(model)),
                    ctx.path_to(ctx, 'OUT_FIGURES', 'cash_equivalent_vs_wealth_{}.png'.format(model)),
            ],
            deps=[
                ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model)),
                # ctx.path_to(ctx, 'OUT_ANALYSIS', 'solutions.mat'),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_1.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_2.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_3.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_4.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_5.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_6.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_7.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_8.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_9.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_10.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_11.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_12.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_13.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_14.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_15.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_16.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_17.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_18.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_19.mat'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', '{}_welfare_analysis_20.mat'.format(model)),
                # ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model))
            ],
            append="('{}')".format(model),
            name='{}_{}'.format(source, model)
        )
