def build(ctx):

    ctx(
        features='subst',
        source='conversion_table.tex',
        target=ctx.path_to(ctx, 'OUT_TABLES', 'conversion_table.tex'),
        is_copy=True,
        update_outputs=True
    )
