#! python


def build(ctx):

        ctx(
            features='tex',
            source='Paper_Eric.tex',
            prompt=1,
        )
        ctx.install_files(
            ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
            'Paper_Eric.pdf'
        )
